### ISSUE TITLE
Config file permission error

### ISSUE THREAD

**Issue by catmandx** [cyllective/oauth-labs#1]
The environment:
Docker 27.3.1
Debian 12
golang 1.23.3

I ran the commands and the management containers are up but clients and servers containers aren't, they reported permission errors. Relevant logs:
```
client-00-1  | 2024/12/03 17:39:24 failed to load configuration from /app/config.yaml: open /app/config.yaml: permission denied
```

Manual fix: 
```
cd oauth-labs
chmod -R o+r docker 
```

**Comment by cydave** [comment]
Thanks for letting me know, sorry you ran into this one.
Looks like my assumption that "everyone runs docker as uid 1000 anyway" was wrong.

The easiest fix would probably be to change the configure step to create config files with world readable permissions. That doesn't sound like the best fix tho. Maybe I'll try and write an entrypoint.sh to fix the permissions before launching the lab...

I'll tinker with something and will update the repo soon.

**Comment by cydave** [comment]
Alrighty, I'm now using gosu to fix the permissions of the config file before spawning the server in [5c97e34c8f18e](https://github.com/cyllective/oauth-labs/commit/5c97e34c8f18ee64a85306037641b12c53b8137a).

If you get the chance please pull and let me know if this resolves the issue for you.

**Comment by cydave** [comment]
Hope that works, if not please reopen.
